apiVersion: v1
kind: ResourceQuota
metadata:
  name: secure-ai-gateway-quota
  namespace: secure-ai-gateway
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "20"
    services: "10"
    persistentvolumeclaims: "5"
    configmaps: "20"
    secrets: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: secure-ai-gateway-limits
  namespace: secure-ai-gateway
spec:
  limits:
  - max:
      cpu: "2"
      memory: 2Gi
    min:
      cpu: 100m
      memory: 128Mi
    default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 250m
      memory: 256Mi
    type: Container
  - max:
      cpu: "4"
      memory: 4Gi
    min:
      cpu: 200m
      memory: 256Mi
    type: Pod
