apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: secure-ai-gateway-scc
  annotations:
    kubernetes.io/description: "SCC for Secure AI Gateway application with restricted permissions"
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: false
allowPrivilegedContainer: false
allowedCapabilities: null
defaultAddCapabilities: null
fsGroup:
  type: MustRunAs
  ranges:
  - min: 1000
    max: 65535
priority: 10
readOnlyRootFilesystem: true
requiredDropCapabilities:
- ALL
runAsUser:
  type: MustRunAsRange
  uidRangeMin: 1000
  uidRangeMax: 65535
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
users: []
groups: []
---
# Command to apply SCC to ServiceAccount:
# oc adm policy add-scc-to-user secure-ai-gateway-scc \
#   -z secure-ai-gateway-sa -n secure-ai-gateway
