apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: secure-ai-gateway-run
  namespace: secure-ai-gateway-cicd
  labels:
    app: secure-ai-gateway
spec:
  pipelineRef:
    name: secure-ai-gateway-pipeline
  params:
  - name: git-url
    value: https://github.com/your-org/secure-ai-gateway.git
  - name: git-revision
    value: main
  - name: image-name
    value: quay.io/secure-ai/secure-ai-gateway
  - name: image-tag
    value: "1.0.0"
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: maven-settings
    configMap:
      name: maven-settings
  - name: docker-credentials
    secret:
      secretName: quay-credentials
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: secure-ai-gateway-listener
  namespace: secure-ai-gateway-cicd
spec:
  serviceAccountName: pipeline
  triggers:
  - name: github-push
    interceptors:
    - ref:
        name: "github"
      params:
      - name: "secretRef"
        value:
          secretName: github-webhook-secret
          secretKey: secret
      - name: "eventTypes"
        value: ["push"]
    bindings:
    - ref: secure-ai-gateway-binding
    template:
      ref: secure-ai-gateway-template
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: secure-ai-gateway-binding
  namespace: secure-ai-gateway-cicd
spec:
  params:
  - name: git-url
    value: $(body.repository.clone_url)
  - name: git-revision
    value: $(body.after)
  - name: git-repo-name
    value: $(body.repository.name)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: secure-ai-gateway-template
  namespace: secure-ai-gateway-cicd
spec:
  params:
  - name: git-url
  - name: git-revision
  - name: git-repo-name
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: secure-ai-gateway-run-
    spec:
      pipelineRef:
        name: secure-ai-gateway-pipeline
      params:
      - name: git-url
        value: $(tt.params.git-url)
      - name: git-revision
        value: $(tt.params.git-revision)
      - name: image-name
        value: quay.io/secure-ai/secure-ai-gateway
      - name: image-tag
        value: $(tt.params.git-revision)
      workspaces:
      - name: shared-workspace
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
      - name: maven-settings
        configMap:
          name: maven-settings
      - name: docker-credentials
        secret:
          secretName: quay-credentials
