apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: secure-ai-gateway-pipeline
  namespace: secure-ai-gateway-cicd
  labels:
    app: secure-ai-gateway
spec:
  params:
  - name: git-url
    type: string
    description: The git repository URL
    default: https://github.com/your-org/secure-ai-gateway.git
  - name: git-revision
    type: string
    description: The git revision to build
    default: main
  - name: image-name
    type: string
    description: The image name to build
    default: quay.io/secure-ai/secure-ai-gateway
  - name: image-tag
    type: string
    description: The image tag
    default: latest
  
  workspaces:
  - name: shared-workspace
  - name: maven-settings
  - name: docker-credentials
  
  tasks:
  
  # Task 1: Clone repository
  - name: fetch-repository
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.git-url)
    - name: revision
      value: $(params.git-revision)
    - name: deleteExisting
      value: "true"
  
  # Task 2: Run unit tests
  - name: run-tests
    taskRef:
      name: maven
      kind: ClusterTask
    runAfter:
    - fetch-repository
    workspaces:
    - name: source
      workspace: shared-workspace
    - name: maven-settings
      workspace: maven-settings
    params:
    - name: GOALS
      value:
      - clean
      - test
      - jacoco:report
  
  # Task 3: Code quality analysis with SonarQube
  - name: code-analysis
    taskRef:
      name: sonarqube-scanner
      kind: Task
    runAfter:
    - run-tests
    workspaces:
    - name: source
      workspace: shared-workspace
    params:
    - name: SONAR_HOST_URL
      value: "https://sonarqube.apps.your-cluster.example.com"
    - name: SONAR_PROJECT_KEY
      value: "secure-ai-gateway"
  
  # Task 4: OWASP Dependency Check
  - name: security-scan
    taskRef:
      name: maven
      kind: ClusterTask
    runAfter:
    - code-analysis
    workspaces:
    - name: source
      workspace: shared-workspace
    - name: maven-settings
      workspace: maven-settings
    params:
    - name: GOALS
      value:
      - org.owasp:dependency-check-maven:check
  
  # Task 5: Build application
  - name: build-application
    taskRef:
      name: maven
      kind: ClusterTask
    runAfter:
    - security-scan
    workspaces:
    - name: source
      workspace: shared-workspace
    - name: maven-settings
      workspace: maven-settings
    params:
    - name: GOALS
      value:
      - clean
      - package
      - -DskipTests
  
  # Task 6: Build and push container image
  - name: build-image
    taskRef:
      name: buildah
      kind: ClusterTask
    runAfter:
    - build-application
    workspaces:
    - name: source
      workspace: shared-workspace
    - name: dockerconfig
      workspace: docker-credentials
    params:
    - name: IMAGE
      value: "$(params.image-name):$(params.image-tag)"
    - name: DOCKERFILE
      value: ./Dockerfile
    - name: CONTEXT
      value: .
    - name: TLSVERIFY
      value: "true"
  
  # Task 7: Image vulnerability scan with Red Hat Advanced Cluster Security
  - name: scan-image
    taskRef:
      name: rox-image-check
      kind: Task
    runAfter:
    - build-image
    params:
    - name: image
      value: "$(params.image-name):$(params.image-tag)"
    - name: rox_central_endpoint
      value: "central.stackrox.svc:443"
    - name: rox_api_token
      value: rox-api-token
  
  # Task 8: Deploy to development
  - name: deploy-to-dev
    taskRef:
      name: openshift-client
      kind: ClusterTask
    runAfter:
    - scan-image
    params:
    - name: SCRIPT
      value: |
        oc apply -f kubernetes/ -n secure-ai-gateway-dev
        oc set image deployment/secure-ai-gateway \
          secure-ai-gateway=$(params.image-name):$(params.image-tag) \
          -n secure-ai-gateway-dev
        oc rollout status deployment/secure-ai-gateway -n secure-ai-gateway-dev
  
  # Task 9: Run integration tests
  - name: integration-tests
    taskRef:
      name: maven
      kind: ClusterTask
    runAfter:
    - deploy-to-dev
    workspaces:
    - name: source
      workspace: shared-workspace
    - name: maven-settings
      workspace: maven-settings
    params:
    - name: GOALS
      value:
      - verify
      - -Pintegration-tests
  
  # Task 10: Deploy to production (with approval)
  - name: deploy-to-prod
    taskRef:
      name: openshift-client
      kind: ClusterTask
    runAfter:
    - integration-tests
    params:
    - name: SCRIPT
      value: |
        oc apply -f kubernetes/ -n secure-ai-gateway-prod
        oc set image deployment/secure-ai-gateway \
          secure-ai-gateway=$(params.image-name):$(params.image-tag) \
          -n secure-ai-gateway-prod
        oc rollout status deployment/secure-ai-gateway -n secure-ai-gateway-prod
